[project]
authors = ["neverorfrog <97flavio.maiorana@gmail.com>"]
channels = ["robostack-staging", "conda-forge"]
description = "Add a short description here"
name = "crazy-neural-mpc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build-acados = "cd crazyflie_mpc_pkg/external/acados && mkdir -p build && cd build && cmake -DACADOS_WITH_QPOASES=ON -DACADOS_WITH_OSQP=ON .. && make -j8"
build = "colcon build --symlink-install"
clean = "rm -rf install log build"
flocking = "ros2 launch crazyflie_flocking_pkg flocking.launch.py"
sim = "cd crazyflie_simulation_pkg/external/crazyflie-firmware && bash tools/crazyflie-simulation/simulator_files/gazebo/launch/sitl_multiagent_square.sh -n 4 -m crazyflie"
swarm = "ros2 launch crazyflie_swarm_pkg swarm.launch.py"
mpc = "ros2 launch crazyflie_mpc_pkg mpc.launch.py"
takeoff = 'ros2 service call /take_off crazyflie_swarm_interfaces/srv/TakeOff "{height: 0.3, duration: 2}"'
land = 'ros2 service call /land crazyflie_swarm_interfaces/srv/Land "{duration: 3}"'

[pypi-dependencies]
cflib = {path = "crazyflie_simulation_pkg/external/crazyflie-lib-python", editable = true}
acados_template = {path = "crazyflie_mpc_pkg/external/acados/interfaces/acados_template", editable = true}
rowan = ">=1.3.2, <2"
transforms3d = ">=0.4.2, <0.5"
omegaconf = ">=2.3.0, <3"
jinja2 = ">=3.1.4, <4"
casadi = "==3.6.4"
torch = "*"
pyyaml = ">=6.0.2,<7"

[dependencies]
python = "==3.11"
numpy = "==1.24"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = ">=75.6.0,<76"
ros-humble-desktop = "==0.10.0"
ros-humble-tf2 = ">=0.25.5,<0.26"
ros-humble-ros-gz-bridge = ">=0.244.9"

[activation]
scripts = ["install/setup.sh"]