dimensions:
  d_eq: 1           # Equilibrium distance [m]
  radius: 0.05      # Radius of the robots [m]
  max_vis_objs: 2   # Max distance of visibility [m]

gains:
  k_r: 4        # Inter-robot force gain
  k_o: 5        # Obstacle avoidance force gain
  k_m: 2        # Migration force gain
  k_al: 1       # Alignment force gain 
  k_l: 0.1      # Velocity gain
  k_a: 0.2      # Acceleration gain 

velocities:
  v_min: 0 #-1e7 #0.05
  v_max: 0.5 #0.5 #1.2
  omega_min: -1.5 #-1e7 #-6
  omega_max: 1.5 #1e7 #6
  a_max: 2 
  
agent:
  num_options: 4
  k: 0.6
  h: 0.2