dt: 0.01
state_publisher_rate: 5.0
led_publisher_rate: 2.0
velocity_publisher_rate: 0.5

crazyflies:
  - name: cf1
    active: False
    uri: radio://0/80/2M/E7E7E7E7E6
    height: 0.2
    multiranger: False
    initial_position:
      x: 0.0
      y: 0.0
      z: 0.0

  - name: cf2
    active: True
    uri: radio://0/80/2M/E7E7E7E7E7
    height: 0.2
    multiranger: True
    initial_position:
      x: 0.0
      y: 0.0
      z: 0.0

  - name: cf3
    active: True
    uri: radio://0/80/2M/E7E7E7E7E8
    height: 0.3
    multiranger: True
    initial_position:
      x: 0.25
      y: 0.0
      z: 0.0

  - name: cf4
    active: False
    uri: radio://0/80/2M/E7E7E7E7E9
    height: 0.2
    multiranger: True
    initial_position:
      x: 0.0
      y: 0.0
      z: 0.0