state_publisher_rate: 5.0
velocity_publisher_rate: 5.0

crazyflies:
  - name: cf1
    active: True
    uri: radio://0/80/2M/E7E7E7E7E6
    takeoff_height: 0.2
    takeoff_duration: 3
    multiranger: True
    initial_position:
      x: 0
      y: -1
      z: 0.0

  - name: cf2
    active: True
    uri: radio://0/80/2M/E7E7E7E7E7
    takeoff_height: 0.3
    takeoff_duration: 3
    multiranger: True
    initial_position:
      x: 0.0
      y: 0.0
      z: 0.0

  - name: cf3
    active: True
    uri: radio://0/80/2M/E7E7E7E7E8
    takeoff_height: 0.3
    takeoff_duration: 3
    multiranger: True
    initial_position:
      x: 0.8
      y: 0.5
      z: 0.0

  - name: cf4
    active: False
    uri: radio://0/80/2M/E7E7E7E7E9
    takeoff_height: 0.5
    takeoff_duration: 3
    multiranger: True
    initial_position:
      x: 0.0
      y: 0.0
      z: 0.0