crazyflie_swarm_node:
  ros__parameters:
  
    crazyflie_robots:
      robot_1:
        name: 'crazyflie_robot_1'
        uri: 'radio://0/80/2M/E7E7E7E7E7'

      robot_2:
        name: 'crazyflie_robot_2'
        uri: 'radio://0/80/2M/E7E7E7E7E8'

    rate: 2.0