# prediction horizon
dt: 0.01
horizon: 100

# parameters for the crazyflie model
quadmodel:
  mass: 0.028
  arm_length: 0.044
  Ixx: 2.3951e-5
  Iyy: 2.3951e-5
  Izz: 3.2347e-5
  cm: 2.4e-6
  tau: 0.08

# weights for the cost function
cost_weights:
  x: 20
  y: 20
  z: 20
  vx: 2
  vy: 2
  vz: 2
  roll: 1
  pitch: 1
  yaw: 1
  roll_c: 1
  pitch_c: 1
  yaw_c: 1
  thrust: 1

# input constraints
input_constraints:
  roll_min: -0.3
  roll_max: 0.3
  pitch_min: -0.3
  pitch_max: 0.3
  yaw_min: -0.3
  yaw_max: 0.3
  thrust_min: 0
  thrust_max: 0.3

# state constraints
state_constraints:
  x_min: -10
  x_max: 10
  y_min: -10
  y_max: 10
  z_min: 0
  z_max: 10
  vx_min: -1
  vx_max: 1
  vy_min: -1
  vy_max: 1
  vz_min: -1
  vz_max: 1
  roll_min: -0.3
  roll_max: 0.3
  pitch_min: -0.3
  pitch_max: 0.3
  yaw_min: -0.3
  yaw_max: 0.3