state_publisher_rate: 5.0
velocity_publisher_rate: 5.0
max_ang_z_rate: 0.4
height: 0.2

crazyflies:
  - name: cf1
    active: True 
  - name: cf2
    active: True
  - name: cf3
    active: True
  - name: cf4
    active: True
